//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace try3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int IdVisita { get; set; }
        public string Motivo { get; set; }
        public string NombreVisitante { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
        public System.TimeSpan HoraEntrada { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public Nullable<int> IdContacto { get; set; }
    
        public virtual Contactos Contactos { get; set; }
    }
}
